"""Schemas for Plotly figures generated by :mod:`malchan.visualization`."""

from typing import Any

from pydantic import BaseModel, ConfigDict, Field


class PlotlyFigureResponse(BaseModel):
    """Serialized Plotly figure with optional UI metadata."""

    model_config = ConfigDict(extra="forbid")

    figure: dict[str, Any]
    metadata: dict[str, Any] = Field(default_factory=dict)


__all__ = ["PlotlyFigureResponse"]
