"""FastAPI routes returning Plotly figures from :mod:`malchan.visualization`."""

from __future__ import annotations

import json
from typing import Any, NoReturn

from fastapi import APIRouter, HTTPException, Query, status

from malchan.app.schemas import PlotlyFigureResponse
from malchan.app.services import ModelNotFoundError, XaiNotReadyError

_VISUALIZATION_ERRORS = (
    ImportError,
    KeyError,
    RuntimeError,
    TypeError,
    ValueError,
    XaiNotReadyError,
)


def _figure_payload(figure: Any) -> dict[str, Any]:
    """Serialize a Plotly figure into a JSON-compatible dictionary."""

    to_json = getattr(figure, "to_json", None)
    if not callable(to_json):
        raise TypeError("Visualization functions must return a Plotly figure.")
    payload = json.loads(to_json())
    if not isinstance(payload, dict):
        raise TypeError("Serialized Plotly figure must be a JSON object.")
    return payload


def _model_dump(response: Any) -> dict[str, Any]:
    """Convert a Pydantic response or mapping-like value to a plain dictionary."""

    if isinstance(response, dict):
        return response
    model_dump = getattr(response, "model_dump", None)
    if callable(model_dump):
        dumped = model_dump(mode="json")
        if isinstance(dumped, dict):
            return dumped
    raise TypeError("Visualization response metadata is not serializable.")


def _raise_http_error(exc: Exception) -> NoReturn:
    """Translate visualization-layer errors to FastAPI responses."""

    if isinstance(exc, ModelNotFoundError):
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Model not found.",
        ) from exc
    if isinstance(exc, XaiNotReadyError):
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail=str(exc),
        ) from exc
    raise HTTPException(
        status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
        detail=str(exc),
    ) from exc


def create_visualization_router(service: Any) -> APIRouter:
    """Create routes that serialize figures generated by ``malchan.visualization``."""

    router = APIRouter(tags=["visualization"])

    @router.get(
        "/models/{model_id}/visualizations/{target}/yy",
        response_model=PlotlyFigureResponse,
    )
    def get_yy_figure(
        model_id: str,
        target: str,
        cv: bool = Query(default=False),
        residual: bool = Query(default=False),
    ) -> PlotlyFigureResponse:
        """Return the standard Y-Y plot or classification confusion matrix."""

        try:
            from malchan.visualization import show_model_diagnostics

            registered = service._get_registered(model_id)
            figure = show_model_diagnostics(
                registered.model,
                target,
                cv=cv,
                residual=residual,
            )
            return PlotlyFigureResponse(
                figure=_figure_payload(figure),
                metadata={
                    "target": target,
                    "cv": cv,
                    "residual": residual,
                },
            )
        except _VISUALIZATION_ERRORS as exc:
            _raise_http_error(exc)

    @router.get(
        "/models/{model_id}/visualizations/{target}/importance",
        response_model=PlotlyFigureResponse,
    )
    def get_importance_figure(
        model_id: str,
        target: str,
        method: str = Query(default="shap"),
        combined: bool = Query(default=True),
        top_n: int = Query(default=20, ge=1, le=1000),
    ) -> PlotlyFigureResponse:
        """Return a Plotly importance chart using the cached XAI response."""

        try:
            from malchan.visualization import show_xai_importance

            response = service.get_xai_importance(
                model_id,
                target,
                method=method,
                combined=combined,
                top_n=top_n,
            )
            figure = show_xai_importance(response, n_bar=top_n)
            return PlotlyFigureResponse(
                figure=_figure_payload(figure),
                metadata={
                    "target": target,
                    "method": method,
                    "combined": combined,
                },
            )
        except _VISUALIZATION_ERRORS as exc:
            _raise_http_error(exc)

    @router.get(
        "/models/{model_id}/visualizations/{target}/shap-beeswarm",
        response_model=PlotlyFigureResponse,
    )
    def get_shap_beeswarm_figure(
        model_id: str,
        target: str,
        output: str | None = Query(default=None),
        top_n: int = Query(default=15, ge=1, le=1000),
    ) -> PlotlyFigureResponse:
        """Return the visualization module's SHAP beeswarm figure."""

        try:
            from malchan.visualization import show_xai_shap_beeswarm

            response = service.get_xai_shap_values(model_id, target)
            payload = _model_dump(response)
            outputs = [str(value) for value in payload.get("output_names", [])]
            selected_output = output or (
                outputs[0] if len(outputs) == 1 else outputs[-1] if outputs else None
            )
            figure = show_xai_shap_beeswarm(
                response,
                n_shap_top=top_n,
                target_item=selected_output,
            )
            return PlotlyFigureResponse(
                figure=_figure_payload(figure),
                metadata={
                    "target": target,
                    "outputs": outputs,
                    "selected_output": selected_output,
                },
            )
        except _VISUALIZATION_ERRORS as exc:
            _raise_http_error(exc)

    @router.get(
        "/models/{model_id}/visualizations/{target}/pdp",
        response_model=PlotlyFigureResponse,
    )
    def get_pdp_figure(
        model_id: str,
        target: str,
        feature: str = Query(min_length=1),
        output: str | None = Query(default=None),
        include_ice: bool = Query(default=False),
        max_ice: int = Query(default=30, ge=1, le=300),
    ) -> PlotlyFigureResponse:
        """Return the visualization module's one-dimensional PDP/ICE figure."""

        try:
            from malchan.visualization import show_xai_pd_and_ice

            response = service.get_xai_pdp(
                model_id,
                target,
                feature,
                include_ice=include_ice,
                max_ice=max_ice,
            )
            payload = _model_dump(response)
            outputs = [
                str(item.get("name"))
                for item in payload.get("series", [])
                if isinstance(item, dict) and item.get("name") is not None
            ]
            selected_output = output or (
                outputs[0] if len(outputs) == 1 else outputs[-1] if outputs else None
            )
            figure = show_xai_pd_and_ice(
                response,
                series_name=selected_output,
                ice=include_ice,
                max_ice=max_ice,
            )
            return PlotlyFigureResponse(
                figure=_figure_payload(figure),
                metadata={
                    "target": target,
                    "feature": feature,
                    "outputs": outputs,
                    "selected_output": selected_output,
                    "include_ice": include_ice,
                },
            )
        except _VISUALIZATION_ERRORS as exc:
            _raise_http_error(exc)

    @router.get(
        "/models/{model_id}/visualizations/{target}/pdp-2d",
        response_model=PlotlyFigureResponse,
    )
    def get_pdp_2d_figure(
        model_id: str,
        target: str,
        feature_x: str = Query(min_length=1),
        feature_y: str = Query(min_length=1),
        output: str | None = Query(default=None),
    ) -> PlotlyFigureResponse:
        """Return a two-dimensional PDP generated by the visualization module."""

        try:
            from malchan.visualization import show_model_pd_2d, visualization_outputs

            registered = service._get_registered(model_id)
            outputs = visualization_outputs(registered.model, target)
            if output is not None and output not in outputs:
                raise ValueError(
                    f"Unknown visualization output {output!r}. Available: {outputs}"
                )
            selected_output = output or (
                outputs[0] if len(outputs) == 1 else outputs[-1] if outputs else None
            )
            output_index = (
                outputs.index(selected_output)
                if selected_output is not None and selected_output in outputs
                else -1
            )
            figure = show_model_pd_2d(
                registered.model,
                target,
                [feature_x, feature_y],
                output_index=output_index,
            )
            return PlotlyFigureResponse(
                figure=_figure_payload(figure),
                metadata={
                    "target": target,
                    "feature_x": feature_x,
                    "feature_y": feature_y,
                    "outputs": outputs,
                    "selected_output": selected_output,
                },
            )
        except _VISUALIZATION_ERRORS as exc:
            _raise_http_error(exc)

    return router


__all__ = ["create_visualization_router"]
